### ISSUE TITLE
If  the input be filters with the null value, we will encounter an error.

### ISSUE THREAD

**Issue by scmorfi** [mohammad-fouladgar/eloquent-builder#12]
```php
[
'one',
'two'=>'',
'three'=>null
]
```
If the input be filters with the null value, we will encounter an error.
the query will encounter with 'Filter Not Found' error.
Is it better to clear the input arguments before applying?

**Comment by mohammad-fouladgar** [comment]
Could you submit a fully tested PR that fixes this?
