### ISSUE TITLE
USAGE WITH LUMEN

### ISSUE THREAD

**Issue by arashifunsho** [mohammad-fouladgar/eloquent-builder#17]
Hello, this is quite an impressive package. Good Job.
I want to use this in one of my Lumen projects and will like to know if this can be integrated with Lumen as is; or it requires some special configurations.

Thank you

**Comment by arashifunsho** [comment]
Also, within the filter, can the query be based on a MYSQL full-text search?

**Comment by mohammad-fouladgar** [comment]
Hi @arashifunsho.
I have not used it yet and not tested on the  Lumen! but I do not think it needs a special configuration.
In the near future, I try to test Lumen too.

> Also, within the filter, can the query be based on a MYSQL full-text search?

Yes you can make a filter based on a full-text search. But this package is not created for full-text search.
You can use either algolia or elastic-search for it.

Thank you for noticing

**Comment by arashifunsho** [comment]
Thanks
