### ISSUE TITLE
Filter not found

### ISSUE THREAD

**Issue by onebruno** [mohammad-fouladgar/eloquent-builder#22]
{
    "code": 500,
    "message": "Filter not found. in /var/www/reagencyv2back/vendor/illuminate/support/helpers.php:1060",
    "trace": [
        {
            "namespace": "",
            "short_class": "",
            "class": "",
            "type": "",
            "function": "",
            "file": "/var/www/reagencyv2back/vendor/illuminate/support/helpers.php",
            "line": 1060,
            "args": []
        },
        {
            "namespace": "",
            "short_class": "",
            "class": "",
            "type": "",
            "function": "throw_if",
            "file": "/var/www/reagencyv2back/vendor/mohammad-fouladgar/eloquent-builder/src/Support/Foundation/Concrete/FilterFactory.php",
            "line": 50,
            "args": [
                [
                    "boolean",
                    true
                ],
                [
                    "string",
                    "Fouladgar\\EloquentBuilder\\Exceptions\\NotFoundFilterException"
                ],
                [
                    "string",
                    "Filter not found."
                ]
            ]
        },
        {
            "namespace": "Fouladgar\\EloquentBuilder\\Support\\Foundation\\Concrete",
            "short_class": "FilterFactory",
            "class": "Fouladgar\\EloquentBuilder\\Support\\Foundation\\Concrete\\FilterFactory",
            "type": "->",
            "function": "findFilter",
            "file": "/var/www/reagencyv2back/vendor/mohammad-fouladgar/eloquent-builder/src/Support/Foundation/Concrete/FilterFactory.php",
            "line": 22,
            "args": []
        },
        {
            "namespace": "Fouladgar\\EloquentBuilder\\Support\\Foundation\\Concrete",
            "short_class": "FilterFactory",
            "class": "Fouladgar\\EloquentBuilder\\Support\\Foundation\\Concrete\\FilterFactory",
            "type": "->",
            "function": "make",
            "file": "/var/www/reagencyv2back/vendor/mohammad-fouladgar/eloquent-builder/src/Support/Foundation/Concrete/FilterFactory.php",
            "line": 17,
            "args": [
                [
                    "string",
                    "first_name"
                ],
                [
                    "object",
                    "App\\Models\\Agent"
                ]
            ]
        },
        {
            "namespace": "Fouladgar\\EloquentBuilder\\Support\\Foundation\\Concrete",
            "short_class": "FilterFactory",
            "class": "Fouladgar\\EloquentBuilder\\Support\\Foundation\\Concrete\\FilterFactory",
            "type": "->",
            "function": "factory",
            "file": "/var/www/reagencyv2back/vendor/mohammad-fouladgar/eloquent-builder/src/EloquentBuilder.php",
            "line": 70,
            "args": [
                [
                    "string",
                    "first_name"
                ],
                [
                    "object",
                    "App\\Models\\Agent"
                ]
            ]
        },
        {
            "namespace": "Fouladgar\\EloquentBuilder",
            "short_class": "EloquentBuilder",
            "class": "Fouladgar\\EloquentBuilder\\EloquentBuilder",
            "type": "->",
            "function": "addFilters",
            "file": "/var/www/reagencyv2back/vendor/mohammad-fouladgar/eloquent-builder/src/EloquentBuilder.php",
            "line": 43,
            "args": [
                [
                    "object",
                    "Illuminate\\Database\\Eloquent\\Builder"
                ],
                [
                    "array",
                    {
                        "first_name": [
                            "string",
                            "division"
                        ]
                    }
                ]
            ]
        },

kindly check the logs

**Comment by mohammad-fouladgar** [comment]
@onebruno, Can you submit the code you used or explain more please?

**Comment by mohammad-fouladgar** [comment]
@onebruno Please see this issue #23. It can help you.
