### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by joefazee** [mohammad-fouladgar/eloquent-builder#24]
For some reasons, I can not get this package installed.  I am using Laravel 5.8.10 on the mac with the default composer.json. I have this config as part of my composer.json. `    "minimum-stability": "dev",
    "prefer-stable": true,`

<img width="974" alt="Screenshot 2019-07-07 at 11 35 34 AM" src="https://user-images.githubusercontent.com/1267708/60767170-a59ea480-a0ab-11e9-88af-96f0d1882680.png">

**Comment by mohammad-fouladgar** [comment]
Can you send your composer.json file to check it out please?

**Comment by joefazee** [comment]
Thank you @mohammad-fouladgar  for responding so quickly. Below is my composer.js

`{
    "name": "laravel/laravel",
    "type": "project",
    "description": "The Laravel Framework.",
    "keywords": [
        "framework",
        "laravel"
    ],
    "license": "MIT",
    "require": {
        "php": "^7.1.3",
        "`": "^1.0",
        "fideloper/proxy": "^4.0",
        "geoip2/geoip2": "^2.9",
        "guzzlehttp/guzzle": "~6.0",
        "laravel/framework": "5.8.*",
        "laravel/tinker": "^1.0",
        "predis/predis": "^1.1",
        "propaganistas/laravel-phone": "^4.2",
        "torann/geoip": "^1.0",
        "webpatser/laravel-uuid": "^3.0"

    },
    "require-dev": {
        "barryvdh/laravel-debugbar": "^3.2",
        "beyondcode/laravel-dump-server": "^1.0",
        "filp/whoops": "^2.0",
        "fzaninotto/faker": "^1.4",
        "mockery/mockery": "^1.0",
        "nunomaduro/collision": "^3.0",
        "phpunit/phpunit": "^7.5",
        "wnx/laravel-stats": "^1.9"
    },
    "config": {
        "optimize-autoloader": true,
        "preferred-install": "dist",
        "sort-packages": true
    },
    "extra": {
        "laravel": {
            "dont-discover": []
        }
    },
    "autoload": {
        "psr-4": {
            "App\\": "app/"
        },
        "classmap": [
            "database/seeds",
            "database/factories"
        ]
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        },
        "files": [
            "app/Support/helpers.php"
        ]
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
    "scripts": {
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover --ansi"
        ],
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate --ansi"
        ]
    }
}
`

**Comment by mohammad-fouladgar** [comment]
> Thank you for responding so quickly

You're welcome.
> require": {
           "php": "^7.1.3",
           "`": "^1.0",

Error occurred on the third line. You must remove the **"`": "^1.0",**  from package names.

**Comment by joefazee** [comment]
Sometimes I try to imagine life without the internet and awesome human begins like you. It works. Thank you so much.

**Comment by mohammad-fouladgar** [comment]
I'm glad that I could help you man. Good luck
