### ISSUE TITLE
Filtering HasManyThrough

### ISSUE THREAD

**Issue by joefazee** [mohammad-fouladgar/eloquent-builder#28]
Hello @mohammad-fouladgar ,

Thank you for the fantastic job done so far. I ran into an issue this afternoon trying to filter a has many through relationship.

So I have a project that has applications through another table (roles) and I am trying to filter the applications based on some fields.

Originally I can just do `$applications = $project->find(1)->applications()->paginate(10)` to fetch the paginated result of all the applications that belongs to that project. 

But I want to apply some filtering like by dates, status, etc. I thought I could do

`
$applications =  $project->applications()->with(['profile']);

$result  = EloquentBuilder::to($applications, request()->all('filters'))->paginate(10);
`

The above code produces an error. See attached screenshot. Maybe I am doing something wrong.
<img width="483" alt="Screenshot 2019-07-27 at 6 14 53 PM" src="https://user-images.githubusercontent.com/1267708/61997569-4d9c0200-b09b-11e9-8684-5b724b692a61.png">

**Comment by mohammad-fouladgar** [comment]
Hi @joefazee ,
thank you for kind words.

Try the following code:

```php
$applications = $project->applications()->getQuery();

$result = EloquentBuilder::to(
                $applications, 
                request()->all('filters')
)->paginate(10);
```
Can you submit a PR full tested for resolve this issue?

**Comment by joefazee** [comment]
Thank @mohammad-fouladgar

**Comment by joefazee** [comment]
Hello @mohammad-fouladgar, Sorry I had to reopen the issue which I think has nothing to do with this library but from your example, the ->getQuery(); nullified all the relationships.

For example, I can not do

`
$applications = $project->applications()->with(['media', 'user.profile'])->getQuery();
`

Do you have any idea why ->getQuery() does not allow fetching of relationships? I have googled already but no good response. 

I will close this issue shorty.

Thank you.

**Comment by mohammad-fouladgar** [comment]
Hi @joefazee ,
I'm sorry for the delay, I was very busy in this week.

Please try this way temporarily:
```php
$res = $this->eloquentBuilder
            ->to($project->applications()->select('applications.*')->getQuery())
            ->with(['media'])
            ->get();
```
Feel free for submit a PR for resolve this issue.

**Comment by joefazee** [comment]
Thank you for responding. I have to use the classic approach, for now, maybe later I can refactor.
