### ISSUE TITLE
issue with paginate

### ISSUE THREAD

**Issue by iMohammadd** [mohammad-fouladgar/eloquent-builder#30]
hi mohammad
thank you for your greate and useful package

i have a issue with paginating
how can i use pagination when use your package
i get ```Not found the filter: PageFilter error```

**Comment by mohammad-fouladgar** [comment]
Hi Dear @iMohammadd ,
Thanks so much.

Try this :
```php
$results = EloquentBuilder::to(
User::class,
$your_array_filters
)->paginate();
```
> i get Not found the filter: PageFilter error

Please read full the issues #25 and #23 for resolve.
