### ISSUE TITLE
How to filter array

### ISSUE THREAD

**Issue by odaiderawi** [mohammad-fouladgar/eloquent-builder#36]
Hi there
great job here man

assume i want to filler products based on given array like that :

api/products?filter[categories]=1,2,3,4

where is the numbers is the categories ids

so the apply method could be

$builder->whereIn('category_id', $value);

but i got this error 

![image](https://user-images.githubusercontent.com/36736057/67469034-3cd83980-f654-11e9-8d69-6ae2c9ecb2b2.png)

**Comment by mohammad-fouladgar** [comment]
Hi, thanks man

Are you sure your definition of the filter is correct?  Please read this issue #31 . 
Feel free to any question.

**Comment by muhammedkaraoglu** [comment]
> Hi there
> great job here man
> 
> assume i want to filler products based on given array like that :
> 
> api/products?filter[categories]=1,2,3,4
> 
> where is the numbers is the categories ids
> 
> so the apply method could be
> 
> $builder->whereIn('category_id', $value);
> 
> but i got this error
> 
> ![image](https://user-images.githubusercontent.com/36736057/67469034-3cd83980-f654-11e9-8d69-6ae2c9ecb2b2.png)

`$users = EloquentBuilder::to(   
            User::class,
            $request->only('filter')['filter']
        );`
