### ISSUE TITLE
Global filters

### ISSUE THREAD

**Issue by maryamBazvand** [mohammad-fouladgar/eloquent-builder#37]
Hello! The package is incredible. Congrats on the job!
Now how can make a global filter for all models?

**Comment by mohammad-fouladgar** [comment]
Hi @maryamBazvand , thank you so much!

That's a great idea !!! Can you submit a full test PR for this issue?

**Comment by mohammad-fouladgar** [comment]
We can have something like these : 
```
├── app
├── Console
│   └── Kernel.php
├── EloquentFilters
│   ├── GlobalAFilter.php
│   ├── GlobalBFilter.php
│   └── User
│       ├── AgeMoreThanFilter.php
│       └── GenderFilter.php
└── Exceptions
    └── Handler.php
```
OR :
```sh
├── app
├── Console
│   └── Kernel.php
├── EloquentFilters
│   ├── Global
│   │   ├── GlobalAFilter.php
│   │   └── GlobalBFilter.php
│   └── User
│       ├── AgeMoreThanFilter.php
│       └── GenderFilter.php
└── Exceptions
    └── Handler.php
```

**Comment by ArtemNehoda** [comment]
Hi , nice package. Is this feature already present? it is useful to ignore the pagination filter page=num . My current solution is make PageFilter for any model with simply "return $builder" but it creates too many duplications

**Comment by mohammad-fouladgar** [comment]
Hi, thank you🙏. 
Not yet. 
You should not submit `page` as a filter. 
Look at the example below:
`api/products?filters[color]=black&filters[size]=xl&per_page=20&page=2`
Then :
```php
$result = EloquentBuilder::to(
            Product::class, 
            $request->filters
)->paginate();
```

**Comment by ArtemNehoda** [comment]
@mohammad-fouladgar you're right, thanks :smile:

**Comment by 50bhan** [comment]
This issue will be closed for now.
