### ISSUE TITLE
Select Not Working

### ISSUE THREAD

**Issue by muhammedkaraoglu** [mohammad-fouladgar/eloquent-builder#39]
Sorry, i am not speak english. I'm using a translate. 
My question is that when I use select the **'bakiye'** column does not appear in the BalanceFilter function.
<img width="682" alt="Ekran Resmi 2019-11-06 19 57 07" src="https://user-images.githubusercontent.com/25641500/68320291-bf3f0f80-00d0-11ea-81cb-03b7fe23f2d1.png">

<img width="569" alt="Ekran Resmi 2019-11-06 19 59 54" src="https://user-images.githubusercontent.com/25641500/68320320-cebe5880-00d0-11ea-88d1-dfefd3584d25.png">

<img width="1141" alt="Ekran Resmi 2019-11-06 19 58 58" src="https://user-images.githubusercontent.com/25641500/68320347-dbdb4780-00d0-11ea-8c8c-09ab60e87a1d.png">

**Comment by 50bhan** [comment]
This error means you don't have a table names 'bakiye' because you are using an alias as table name. FYI, there is some rules and limitation about aliases in queries. This is a SQL limitation (you cannot use an alias for a column in a where clause).

**Comment by muhammedkaraoglu** [comment]
But when I don't use filter, the SQL query works. What am I supposed to do when I use a filter ? @50bhan

**Comment by 50bhan** [comment]
Of course it works, because you don't use alias in where clause. But in the filter you have to use where clause and you will face the error. For using filter, you have to manage your situation and not using aliases.

**Comment by mohammad-fouladgar** [comment]
Thanks @50bhan for response

@muhammedkaraoglu you should use the following code:
```php
return $builder->whereRaw('sum (tutar * doviz_kuru) ','<',0)->order... 
```
Please read the `whereRaw` in the laravel official documentation.

**Comment by mohammad-fouladgar** [comment]
This error is related to SQL and I close this.
