### ISSUE TITLE
Custom directory support

### ISSUE THREAD

**Issue by 50bhan** [mohammad-fouladgar/eloquent-builder#51]
Hello @mohammad-fouladgar. 

How can we use the package in custom directories? (not only default directory App\\EloquentFilters\\MODEL-NAME)

**Comment by mohammad-fouladgar** [comment]
Hi @50bhan ,
You can change the default namespace with publish the config file.

Please checkout the documentation : [Namespace With Config file](https://github.com/mohammad-fouladgar/eloquent-builder#with-config-file)

**Comment by 50bhan** [comment]
@mohammad-fouladgar ,

I think you misunderstood my question. Let me put it this way: what if a user wants to use the package in MULTIPLE custom directories?! Apparently now this is not possible, because default namespace in not enough for this situation. 

So I might have an idea to add this feature to the package. What do you suggest? Let me know if you welcome the idea.

**Comment by mohammad-fouladgar** [comment]
@50bhan ,
That is, if we have a **modular** system or **DDD** (_Domain Driven-Development_), we will can customize the filter namespace per domain, I'm right?

**Comment by 50bhan** [comment]
@mohammad-fouladgar ,

Sure, let me get my mind around it then I'll send a PR.

**Comment by mohammad-fouladgar** [comment]
This is a great idea as long as it does not disturb the current structure.

Feel free to submit a fully tested PR.

Good luck Man
