### ISSUE TITLE
message: Non-static method Fouladgar\EloquentBuilder\EloquentBuilder::to() should not be called statically

### ISSUE THREAD

**Issue by realSaeedHassani** [mohammad-fouladgar/eloquent-builder#70]
`Laravel 6.`

What's the problem?

**Comment by mohammad-fouladgar** [comment]
You should use the facade of EloquentBuilder.
Please look at the example usage below:
```php
// Facade usage
use EloquentBuilder;

$users = EloquentBuilder::to(\App\User::class,YOUR_FILTERS)->get();
```

**Comment by mohammad-fouladgar** [comment]
@realSaeedHassani I close this issue. 
If does not resolved the issue, feel free to reopen it.

**Comment by realSaeedHassani** [comment]
Works fine!

**Comment by realSaeedHassani** [comment]
> @realSaeedHassani You should use the facade of EloquentBuilder.
> Please look at the example usage below:
> 
> ```
> // Facade usage
> use EloquentBuilder;
> 
> $users = EloquentBuilder::to(\App\User::class,YOUR_FILTERS)->get();
> ```

Works fine.

**Comment by multiarts** [comment]
Don't solved, Laravel 7.x

> > @realSaeedHassani You should use the facade of EloquentBuilder.
> > Please look at the example usage below:
> > ```
> > // Facade usage
> > use EloquentBuilder;
> > 
> > $users = EloquentBuilder::to(\App\User::class,YOUR_FILTERS)->get();
> > ```
> 
> Works fine.

_Undefined type 'EloquentBuilder'_

**Comment by 50bhan** [comment]
@multiarts Could you give us a view from your code?

**Comment by multiarts** [comment]
<img src="https://i.imgur.com/tQYXoix.png" />

> @multiarts Could you give us a view from your code?

**Comment by 50bhan** [comment]
@multiarts I can't see a good reason for it. Please use it as your first image, then run a `composer dump`. It might related to composer autoload.

**Comment by multiarts** [comment]
> @multiarts I can't see a good reason for it. Please use it as your first image, then run a `composer dump`. It might related to composer autoload.

To solve the problem, I added before the Request facade.
```
use EloquentBuilder;
use Illuminate\Http\Request;
```
