### ISSUE TITLE
Pagination in Search

### ISSUE THREAD

**Issue by boobProgrammer** [mohammad-fouladgar/eloquent-builder#72]
سلام عزیز
من کد زیر را توی searchController استفاده کردم برای ساخت صفحه بندی 
کد کار میکنه ولی وقتی روی دکمه های صفحه بندی میزنم اون موقع تمامی ردیف های دیتابیس را برمیگردونه
`$search = EloquentBuilder::to(
            Domains::class,
            [
                'domain_name' => $request['domain_name'],
                'amount' => $request['amount'],
                'category' => $request['category'],
            ]
        )->paginate(5);`

**Comment by 50bhan** [comment]
@boobProgrammer I can't reproduce your problem. But at first I suggest to follow the documentation: https://github.com/mohammad-fouladgar/eloquent-builder#use-a-filter

`user/search?filter[age_more_than]=25&filter[gender]=male'
And then use them this way: `request()->filter`.

**Comment by mohammad-fouladgar** [comment]
@boobProgrammer 

If you wish to append all current query string values to the pagination links you may use the `withQueryString` method:
```php
{{ $users->withQueryString()->links() }}
```
Please read this section of document: https://laravel.com/docs/7.x/pagination#displaying-pagination-results

**Comment by boobProgrammer** [comment]
thank you mohammad
this work'd to me
Thankssssssssssss
