### ISSUE TITLE
Problem with filter zero

### ISSUE THREAD

**Issue by merudda** [mohammad-fouladgar/eloquent-builder#77]
Hello, 
thank you for the job!

I've problem when filter has value 0:
// GET /filter?step=0&work=1&...
// GET /filter?step[]=0&...

The param step in ServiceProvider->registerMacros is excluded because it is considered empty, instead it is a valid value in my DB.

Is there any solution?

**Comment by grudge61** [comment]
same problem here..

Is there anyone who knows how to solve it? @mohammad-fouladgar any advice or solutions?

Thanks for the reply

**Comment by 50bhan** [comment]
@merudda @grudge61 Thanks for reporting this issue. Yes you are right. It's a bug and I'll try to fix it.

**Comment by mohammad-fouladgar** [comment]
Please use the latest version(v2.2.2).
