### ISSUE TITLE
Should add support for Laravel 8.x

### ISSUE THREAD

**Issue by stefvanesch** [mohammad-fouladgar/eloquent-builder#82]

**Comment by 50bhan** [comment]
@stefvanesch Hi, Thank you for opening this issue. Can you send a PR for this?

**Comment by 50bhan** [comment]
@stefvanesch Awesome! Thanks a lot.

**Comment by stefvanesch** [comment]
@50bhan When will you release the new version for this? I really want to upgrade a project 👍. Don't know if you've noticed but a changes the `CHANGELOG.md` and named it version `2.3.0`.

**Comment by 50bhan** [comment]
@stefvanesch Yes I've noticed. We will release the new version today.

cc @mohammad-fouladgar

**Comment by stefvanesch** [comment]
Awesome! Looking forward to is 😬

**Comment by mohammad-fouladgar** [comment]
@stefvanesch @50bhan  Thanks, guys.  I'll release a new version soon.

**Comment by stefvanesch** [comment]
@mohammad-fouladgar Any guys on when it will be released?

**Comment by mohammad-fouladgar** [comment]
@stefvanesch I'm sorry for the delay. I wanted to release a new version yesterday, But unfortunately, there was no time.
I have released a new version 2.3.0 and you can use it.

Thank you for your patience.

**Comment by stefvanesch** [comment]
Thanks!!
