### ISSUE TITLE
PHP 8 support?

### ISSUE THREAD

**Issue by mmubasharsheikh** [mohammad-fouladgar/eloquent-builder#89]
Hello, do you have any plans to support php 8?
![image](https://user-images.githubusercontent.com/11888803/108119898-4778d680-70c2-11eb-98a3-73e8bbb21519.png)

Thank you for your work

**Comment by 50bhan** [comment]
@mmubasharsheikh Thank you for your report. We will add this very soon!

**Comment by mohammad-fouladgar** [comment]
@mmubasharsheikh Please install from the `master` branch. I will release a new version as soon as possible.
