### ISSUE TITLE
کارکرد نادرست برای محدوده قیمت

### ISSUE THREAD

**Issue by shayanes777** [mohammad-fouladgar/eloquent-builder#92]
سلام همه چیز رعایت شده و بدون ارور انجام میشه ولی شرط رعایت نمیشه و به درستی اعمال نمیشه

controller
`$files = EloquentBuilder::to(File::class, $request->all())->orderBy('id','desc')->paginate(2);`

filter
```php
class GheymatkolMoreThanFilter extends Filter
{
    public function apply(Builder $builder, $value): Builder
    {
        return $builder->where('gheymatkol', '>', $value);
    }
}
```

view input
`<input type="text" class="form-control" id="gheymataz" name="gheymatkol_more_than">`

**Comment by mohammad-fouladgar** [comment]
@shayanes777 سلام. برسی کن ببین فیلتر کال میشه یا نه:
```php
class GheymatkolMoreThanFilter extends Filter
{
    public function apply(Builder $builder, $value): Builder
    {
        dd('Called: ',$value);
        return $builder->where('gheymatkol', '>', $value);
    }
}
```

**Comment by shayanes777** [comment]
بله میشه

**Comment by mohammad-fouladgar** [comment]
@shayanes777
احتمال زیاد رکوردی وجود نداره.برای اطمینان این کد رو اضافه کنید ببینید لاگ چی میوفته.
Controller:
```php
\DB::connection()->enableQueryLog();
$files = EloquentBuilder::to(File::class, $request->all())->orderBy('id','desc')->paginate(2);
dd(\DB::getQueryLog(),$files);
```

**Comment by shayanes777** [comment]
رکورد هم وجود داره

**Comment by mohammad-fouladgar** [comment]
@shayanes777  میشه لطفا خروجی لاگ رو ارسال کنید؟
`dd(\DB::getQueryLog(),$files);‍‍`

**Comment by shayanes777** [comment]
array:2 [▼
  0 => array:3 [▶]
  1 => array:3 [▶]
]
Illuminate\Pagination\LengthAwarePaginator {#1634 ▼
  #total: 2
  #lastPage: 1
  #items: Illuminate\Database\Eloquent\Collection {#1629 ▶}
  #perPage: 2
  #currentPage: 1
  #path: "http://127.0.0.1:8000/allfiles"
  #query: []
  #fragment: null
  #pageName: "page"
  +onEachSide: 3
  #options: array:2 [▶]
}

**Comment by mohammad-fouladgar** [comment]
@shayanes777 داخل آرایه ها مهم هستش. من کوئری رو میخوام ببینم.
‍‍‍
```php
array:2 [▼
  0 => array:3 [▼
    "query" => "select count(*) as aggregate from "users" where "email" like ?"
    "bindings" => array:1 [▼
      0 => "%a%"
    ]
    "time" => 0.48
  ]
  1 => array:3 [▼
    "query" => "select * from "users" where "email" like ? limit 2 offset 0"
    "bindings" => array:1 [▼
      0 => "%a%"
    ]
    "time" => 0.1
  ]
]
```
هرجا آرایه یا کالکشن هست باز کنید بعد کپی و ارسال کنید

**Comment by shayanes777** [comment]
array:1 [▼
  0 => array:3 [▼
    "query" => "select count(*) as aggregate from `files` where `gheymatkol` > ?"
    "bindings" => array:1 [▼
      0 => "4555556"
    ]
    "time" => 0.59
  ]
]

**Comment by shayanes777** [comment]
دو ایتم داخل جدول در دیتابیس هست که یکی از دو ایتم بیشتر از اون عدد هستش ولی نمیارتش

**Comment by mohammad-fouladgar** [comment]
با این کوئری :
`select count(*) as aggregate from files where gheymatkol > '4555556'`
یعنی فیلتر اعمال شده ولی خروجی نداره. یعنی مشکل از جایی دیگه باید باشه.
به من ایمیل بزنید تا از روش دیگه مشکل رو برسی کنیم
fouladgar.dev@gmail.com

**Comment by shayanes777** [comment]
احتمالا مشکل از دیتابیس من هستش پس. ممنون از وقتی که گذاشتید همچنین از ساختن همچین پکیج کارآمدی

**Comment by mohammad-fouladgar** [comment]
اول بدون استفاده از پکیج کوئری بزنید مطمئن بشید همه چی درسته یا نه.
خواهش میکنم. موفق باشید
