### ISSUE TITLE
Problem NotFoundFilterException on server

### ISSUE THREAD

**Issue by BehroozBvk** [mohammad-fouladgar/eloquent-builder#94]
Hi, I use this package locally well, but when I run it on the server, I get this error:
```
Fouladgar\EloquentBuilder\Exceptions\NotFoundFilterException
Not found the filter: QFilter
```
Please check.
Thanks.

**Comment by mohammad-fouladgar** [comment]
Please check out this commnet: https://github.com/mohammad-fouladgar/eloquent-builder/pull/85#issuecomment-695785432

**Comment by BehroozBvk** [comment]
> Please check out this comment: [#85 (comment)](https://github.com/mohammad-fouladgar/eloquent-builder/pull/85#issuecomment-695785432)

thanks solved.
