### ISSUE TITLE
Update PHP version requirement

### ISSUE THREAD

**Issue by james-lukensow** [mohammad-fouladgar/eloquent-builder#95]
Noting that I can not upgrade my Laravel 8 application to Laravel 9 due to the PHP version requirements by this package. Any chance you can bump the max php version to 8.1?

**Comment by 50bhan** [comment]
@james-lukensow Thank you for reporting this. I have an open [PR](https://github.com/mohammad-fouladgar/eloquent-builder/pull/96) for this. After the merge, we're gonna release a new version.

**Comment by mohammad-fouladgar** [comment]
@james-lukensow The V4.0.0 has been released. Now you can use this version for PHP8.* and Laravel 9.* .

**Comment by james-lukensow** [comment]
Great news, thanks 👍
